/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pnwwuskfebfojkzxigxiyemjim.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-1:080c2f8f-a9f3-4c1c-a920-f9fef69d23a2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9szD23ASk",
    "aws_user_pools_web_client_id": "5c8jc9h3067oupkk06aqlcrgsr",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "questionimages131553-kwizz",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "predictions": {
        "interpret": {
            "interpretText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "type": "LANGUAGE"
                }
            }
        }
    }
};


export default awsmobile;
